### ISSUE TITLE
Hitting a NullPointerException while creating UML

### ISSUE THREAD

**Issue by karthik134** [davidmoten/openapi-to-plantuml#81]
I am running into the following exception when trying to convert a JSON Swagger structure

[ERROR] java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.github.davidmoten.oas3.internal.PathsHelper.toModelParameter(PathsHelper.java:130) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.internal.PathsHelper.lambda$toModelParameters$4(PathsHelper.java:76) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[?:1.8.0_221]
	at com.github.davidmoten.oas3.internal.PathsHelper.toModelParameters(PathsHelper.java:77) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.internal.PathsHelper.lambda$toModelPath$2(PathsHelper.java:62) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[?:1.8.0_221]
	at com.github.davidmoten.oas3.internal.PathsHelper.toModelPath(PathsHelper.java:69) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.internal.PathsHelper.lambda$paths$0(PathsHelper.java:47) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
	at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[?:1.8.0_221]
	at com.github.davidmoten.oas3.internal.PathsHelper.paths(PathsHelper.java:49) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.internal.PathsHelper.toModel(PathsHelper.java:37) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.puml.Converter.openApiToPuml(Converter.java:65) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]
	at com.github.davidmoten.oas3.puml.Converter.openApiToPuml(Converter.java:57) ~[openapi-to-plantuml-0.1.12-SNAPSHOT.jar:?]

The Swagger structure is as below.
> {
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0",
    "title" : "Summary about the new REST service.",
    "description" : "Summary about the new REST service."
  },
  "host" : "localhost:8089",
  "basePath" : "/",
  "schemes" : [ "http" ],
  "paths" : {
    "/profiles" : {
      "get" : {
        "description" : "",
        "operationId" : "get-profiles",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "UUID",
          "in" : "query",
          "description" : "",
          "type" : "string",
          "required" : false
        } ],
        "responses" : {
          "200" : {
            "description" : "a Profile to be returned",
            "schema" : {
              "$ref" : "#/definitions/Profile"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "Profile" : {
      "type" : "object",
      "required" : [ "PROFILE_ID", "UUID", "PHOTO_FILE_TYPE", "PHOTO_UPD_DT", "PHOTO" ],
      "properties" : {
        "UUID" : {
          "type" : "string"
        },
        "PROFILE_ID" : {
          "type" : "string"
        },
        "PHOTO" : {
          "type" : "string"
        },
        "PHOTO_FILE_TYPE" : {
          "type" : "string"
        },
        "PHOTO_UPD_DT" : {
          "type" : "string"
        }
      }
    }
  }
}

**Comment by davidmoten** [comment]
The problem is this is a Swagger 2.0 definition not an OpenAPI v3 definition. The structure is different for OpenAPI v3.

You can see the problems in https://apitools.dev/swagger-parser/online/ by pasting in your document and changing the field `swagger: 2.0` to `openapi: 3.0.1`
